import { Roboto, Roboto_Mono } from "next/font/google"; // Exemple de polices
import "./globals.css";
import provider from "./provider";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Optionnel : si tu veux plusieurs graisses
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased`}
      >
        <provider>
          {children}
        </provider>
      </body>
    </html>
  );
}
