import { Roboto, Roboto_Mono } from "next/font/google"; // Exemple de polices
import "./globals.css";
import provider from "./provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import EditorHeader from "@/components/custom/EditorHeaader";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Optionnel : si tu veux plusieurs graisses
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
      <Provider>
          
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  </ClerkProvider>
  );
}
